url: "https://thegeekreview.net" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
markdown: kramdown
permalink: /:title/
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-seo-tag

paginate: 5
paginate_path: "/page/:num"

# SEO TAG Settings
title: The Geek Review
description: Don't buy pig in a poke and read my reviews!


# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages


# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed
